# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Path to pwendok
export PWENDOK=~/.pwendok

# Configuration
    # Theme
ZSH_THEME="leny"
    # Custom folder location
ZSH_CUSTOM=$PWENDOK/zsh/custom
    # Plugins
plugins=(git brew depo docker docker-compose encode64 leny-git-prompt npm sote)

source $ZSH/oh-my-zsh.sh
